# Script was generated by ChatGPT with minor modification. 
import os
import subprocess
import pandas as pd
from tqdm import tqdm

CSV_PATH = "assets/vgg/vggsound.csv"
OUTPUT_DIR = "vggsound_20k"
TARGET_TOTAL = 20000


for split in ["train", "test"]:
    os.makedirs(f"{OUTPUT_DIR}/{split}/video", exist_ok=True)
    os.makedirs(f"{OUTPUT_DIR}/{split}/audio", exist_ok=True)

os.makedirs(f"{OUTPUT_DIR}/tmp", exist_ok=True)

# Load csv
df = pd.read_csv(CSV_PATH, header=None)
df.columns = ["youtube_id", "start_sec", "label", "split"]

# Shuffle dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Split properly
train_df = df[df["split"] == "train"]
test_df = df[df["split"] == "test"]

print(f"Total available: {len(df)}")
print(f"Train available: {len(train_df)}")
print(f"Test available: {len(test_df)}")


def download_clip(youtube_id, start_sec, split):
    tmp_video = f"{OUTPUT_DIR}/tmp/{youtube_id}.mp4"
    
    video_out = f"{OUTPUT_DIR}/{split}/video/{youtube_id}.mp4"
    audio_out = f"{OUTPUT_DIR}/{split}/audio/{youtube_id}.wav"

    url = f"https://www.youtube.com/watch?v={youtube_id}"

    try:
        # Download video
        subprocess.run([
            "yt-dlp",
            "-f", "mp4",
            "-o", tmp_video,
            url
        ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        if not os.path.exists(tmp_video):
            return False

        # Trim video (NO AUDIO)
        subprocess.run([
            "ffmpeg",
            "-y",
            "-ss", str(start_sec),
            "-i", tmp_video,
            "-t", "10",
            "-an",
            "-c:v", "libx264",
            video_out
        ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        # Extract audio ONLY
        subprocess.run([
            "ffmpeg",
            "-y",
            "-ss", str(start_sec),
            "-i", tmp_video,
            "-t", "10",
            "-vn",
            "-acodec", "pcm_s16le",
            "-ar", "16000",
            "-ac", "1",
            audio_out
        ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        os.remove(tmp_video)
        return True

    except Exception:
        if os.path.exists(tmp_video):
            os.remove(tmp_video)
        return False


train_count = 0
test_count = 0
total_count = 0

train_iter = iter(train_df.itertuples())
test_iter = iter(test_df.itertuples())

print("\nDownloading dataset...\n")

with tqdm(total=TARGET_TOTAL) as pbar:
    while total_count < TARGET_TOTAL:
        # Alternate between train and test for balance
        for split_name, iterator in [("train", train_iter), ("test", test_iter)]:
            if total_count >= TARGET_TOTAL:
                break

            try:
                row = next(iterator)
            except StopIteration:
                continue

            success = download_clip(row.youtube_id, row.start_sec, split_name)

            if success:
                if split_name == "train":
                    train_count += 1
                else:
                    test_count += 1

                total_count += 1
                pbar.update(1)


print("\n========== DONE ==========")
print(f"Train clips: {train_count}")
print(f"Test clips: {test_count}")
print(f"Total clips: {total_count}")